// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core"
import { ExpirationPlugin } from "workbox-expiration"
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching"
import { registerRoute } from "workbox-routing"
import {
  StaleWhileRevalidate,
  CacheFirst,
  NetworkOnly,
} from "workbox-strategies"
import { CacheableResponsePlugin } from "workbox-cacheable-response"
import { BackgroundSyncPlugin } from "workbox-background-sync"
import { buildCacheKey } from "@tropo/core"

clientsClaim()

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST)

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$")
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith("/_")) {
      return false
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false
    } // Return true to signal that we want to use the handler.

    return true
  },
  createHandlerBoundToURL(
    import.meta.env.BASE_URL.replace(/\/$/, "") + "/index.html",
  ),
)

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  }),
)

// Cache album covers and artwork images using CacheFirst strategy
registerRoute(
  ({ url }) =>
    url.pathname.startsWith("/api/discogs-image/") ||
    url.origin.includes("discogs") ||
    /\.(jpe?g|png|webp)($|\?)/i.test(url.pathname),
  new CacheFirst({
    cacheName: buildCacheKey("item-covers"),
    plugins: [
      new ExpirationPlugin({ maxEntries: 500 }),
      new CacheableResponsePlugin({ statuses: [200] }),
    ],
  }),
)

// Background Sync for offline provider updates
const bgSyncPlugin = new BackgroundSyncPlugin("provider-queue", {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours
})

registerRoute(
  ({ url }) =>
    url.pathname.startsWith("/api/") && !url.pathname.startsWith("/api/leds"),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  "POST",
)

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
// It also allows the app to trigger a manual replay of background sync
// queues (useful on iOS)
self.addEventListener("message", async (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting()
  } else if (event.data && event.data.type === "REPLAY_QUEUES") {
    console.log("[ServiceWorker] Manual replay of background sync triggered")
    if (bgSyncPlugin && bgSyncPlugin._queue) {
      await bgSyncPlugin._queue.replayRequests()
    }
  }
})
