services:
  tropoaudio:
    build:
      context: .
      args:
        APP_NAME: tropoaudio
        PORT: 3000
    ports:
      - "${TROPOAUDIO_PORT:-3000}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: apps/tropoaudio/.env
        required: false

  tropocine:
    build:
      context: .
      args:
        APP_NAME: tropocine
        PORT: 3001
    ports:
      - "${TROPOCINE_PORT:-3001}:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: apps/tropocine/.env
        required: false

  tropobiblio:
    build:
      context: .
      args:
        APP_NAME: tropobiblio
        PORT: 3002
    ports:
      - "${TROPOBIBLIO_PORT:-3002}:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: apps/tropobiblio/.env
        required: false

