import { clientsClaim } from "workbox-core"
import { ExpirationPlugin } from "workbox-expiration"
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching"
import { registerRoute } from "workbox-routing"
import { StaleWhileRevalidate, CacheFirst } from "workbox-strategies"
import { CacheableResponsePlugin } from "workbox-cacheable-response"
import { buildCacheKey } from "@tropo/core"

clientsClaim()

// Precache all assets generated by Vite build process
precacheAndRoute(self.__WB_MANIFEST)

// App Shell routing: fulfill all navigation requests with index.html
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$")
registerRoute(
  ({ request, url }) => {
    if (request.mode !== "navigate") {
      return false
    }
    if (url.pathname.startsWith("/_")) {
      return false
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false
    }
    return true
  },
  createHandlerBoundToURL(
    import.meta.env.BASE_URL.replace(/\/$/, "") + "/index.html",
  ),
)

// Runtime caching for same-origin icons and images
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"),
  new StaleWhileRevalidate({
    cacheName: buildCacheKey("images"),
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  }),
)

// Cache book covers and artwork images using CacheFirst strategy
registerRoute(
  ({ url }) =>
    url.pathname.startsWith("/api/proxy-image") ||
    url.pathname.includes("-image/") ||
    /\.(jpe?g|png|webp|avif)($|\?)/i.test(url.pathname),
  new CacheFirst({
    cacheName: buildCacheKey("item-covers"),
    plugins: [
      new ExpirationPlugin({ maxEntries: 500 }),
      new CacheableResponsePlugin({ statuses: [200] }),
    ],
  }),
)

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting()
  }
})
