import { clientsClaim } from "workbox-core"
import { ExpirationPlugin } from "workbox-expiration"
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching"
import { registerRoute } from "workbox-routing"
import {
  StaleWhileRevalidate,
  CacheFirst,
  NetworkOnly,
} from "workbox-strategies"
import { CacheableResponsePlugin } from "workbox-cacheable-response"
import { BackgroundSyncPlugin } from "workbox-background-sync"
import { buildCacheKey } from "@tropo/core"

clientsClaim()

// Precache all assets generated by Vite build process
precacheAndRoute(self.__WB_MANIFEST)

// App Shell routing: fulfill all navigation requests with index.html
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$")
registerRoute(
  ({ request, url }) => {
    if (request.mode !== "navigate") {
      return false
    }
    if (url.pathname.startsWith("/_")) {
      return false
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false
    }
    return true
  },
  createHandlerBoundToURL(
    import.meta.env.BASE_URL.replace(/\/$/, "") + "/index.html",
  ),
)

// Runtime caching for same-origin icons and images
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"),
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  }),
)

// Cache movie posters and artwork images using CacheFirst strategy
registerRoute(
  ({ url }) =>
    url.origin.includes("tmdb") ||
    url.pathname.startsWith("/api/proxy-image") ||
    /\.(jpe?g|png|webp)($|\?)/i.test(url.pathname),
  new CacheFirst({
    cacheName: buildCacheKey("item-covers"),
    plugins: [
      new ExpirationPlugin({ maxEntries: 500 }),
      new CacheableResponsePlugin({ statuses: [200] }),
    ],
  }),
)

// Background Sync for offline provider updates
const bgSyncPlugin = new BackgroundSyncPlugin("provider-queue", {
  maxRetentionTime: 24 * 60,
})

registerRoute(
  ({ url }) => url.pathname.startsWith("/api/"),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  "POST",
)

// Allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({ type: 'SKIP_WAITING' })
self.addEventListener("message", async (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting()
  } else if (event.data && event.data.type === "REPLAY_QUEUES") {
    if (bgSyncPlugin && bgSyncPlugin._queue) {
      await bgSyncPlugin._queue.replayRequests()
    }
  }
})
