import { defineConfig, loadEnv } from "vite"
import react from "@vitejs/plugin-react"
import { VitePWA } from "vite-plugin-pwa"

import fs from "fs"

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "")
  const packageJson = JSON.parse(fs.readFileSync("./package.json", "utf8"))

  // Derive User-Agent string dynamically from package metadata
  const appName =
    packageJson.name === "tropodisc" ? "TropoDisc" : packageJson.name
  const userAgent = `${appName}/${packageJson.version} (${packageJson.homepage})`

  const proxy = {}
  if (env.VITE_SET_LEDS === "yes" && env.VITE_AUDIOLIBRARY_URL) {
    const ledProxyOptions = {
      target: env.VITE_AUDIOLIBRARY_URL,
      changeOrigin: true,
      headers: {
        Connection: "close",
      },
    }
    proxy["/api/leds"] = {
      ...ledProxyOptions,
      rewrite: (path) => path.replace(/^\/api\/leds/, "/leds"),
    }
    proxy["/api/ping"] = {
      ...ledProxyOptions,
      rewrite: (path) => path.replace(/^\/api\/ping/, "/ping"),
    }
    proxy["/api/ruler"] = {
      ...ledProxyOptions,
      rewrite: (path) => path.replace(/^\/api\/ruler/, "/ruler"),
    }
  }

  if (env.DISCOGS_TOKEN) {
    const token = env.DISCOGS_TOKEN
    proxy["/api/discogs"] = {
      target: "https://api.discogs.com",
      changeOrigin: true,
      rewrite: (path) => path.replace(/^\/api\/discogs/, ""),
      headers: {
        Authorization: `Discogs token=${token}`,
        "User-Agent": userAgent,
      },
      configure: (proxyServer) => {
        proxyServer.on("proxyRes", (proxyRes) => {
          delete proxyRes.headers["set-cookie"]
        })
      },
    }
  }

  proxy["/api/discogs-image"] = {
    target: "https://i.discogs.com",
    changeOrigin: true,
    rewrite: (path) => path.replace(/^\/api\/discogs-image/, ""),
    headers: {
      "User-Agent": userAgent,
    },
    configure: (proxyServer) => {
      proxyServer.on("proxyRes", (proxyRes) => {
        delete proxyRes.headers["set-cookie"]
        proxyRes.headers["access-control-allow-origin"] = "*"
      })
    },
  }

  // Image proxy middleware to bypass CORS for client-side ZIP export
  const imageProxyPlugin = {
    name: "image-proxy-plugin",
    configureServer(server) {
      server.middlewares.use("/api/proxy-image", async (req, res) => {
        const targetUrl = new URL(req.url, "http://localhost").searchParams.get(
          "url",
        )

        if (!targetUrl) {
          res.statusCode = 400
          res.end("Missing url parameter")
          return
        }

        try {
          const response = await fetch(targetUrl, {
            headers: {
              "User-Agent": userAgent,
            },
          })

          if (!response.ok) {
            res.statusCode = response.status
            res.end("Failed to fetch image from target server")
            return
          }

          const arrayBuffer = await response.arrayBuffer()
          const buffer = Buffer.from(arrayBuffer)

          res.setHeader("Access-Control-Allow-Origin", "*")
          res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS")
          res.setHeader(
            "Content-Type",
            response.headers.get("content-type") || "image/jpeg",
          )
          res.end(buffer)
        } catch (err) {
          res.statusCode = 500
          res.end(`Image proxy error: ${err.message}`)
        }
      })
    },
  }

  // Emit .htaccess and Apache configuration fragments for deployments
  const apacheConfigPlugin = {
    name: "apache-config-plugin",
    generateBundle() {
      const htaccessContent = `# Auto-generated by Vite build
<IfModule mod_headers.c>
    # Set dynamic User-Agent for reverse proxy requests
    RequestHeader set User-Agent "${userAgent}"

    # Cache control for service worker and entry point
    <Files "service-worker.js">
        Header set Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    </Files>
    <Files "index.html">
        Header set Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    </Files>
</IfModule>

# Single Page Application routing fallback
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\\.html$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
</IfModule>

# Deny direct web access to server configuration and log files
<FilesMatch "\\.(conf|log)$">
    Require all denied
</FilesMatch>
`
      this.emitFile({
        type: "asset",
        fileName: ".htaccess",
        source: htaccessContent,
      })

      const headersContent = `# Auto-generated by Vite build
<IfModule mod_headers.c>
    # Set dynamic User-Agent for reverse proxy requests
    RequestHeader set User-Agent "${userAgent}"

    # Strip upstream Set-Cookie headers to prevent invalid domain cookie errors in browsers
    Header unset Set-Cookie
    Header always unset Set-Cookie
</IfModule>
`
      this.emitFile({
        type: "asset",
        fileName: "headers.conf",
        source: headersContent,
      })
    },
  }

  // Extract default theme surface color from CSS tokens (single source of truth)
  const themesCssPath = new URL(
    "../../packages/react/src/themes.css",
    import.meta.url,
  )
  const themesCss = fs.readFileSync(themesCssPath, "utf8")
  const surfaceMatch = themesCss.match(/--tropo-surface:\s*(#[0-9a-fA-F]{3,8})/)
  const defaultThemeColor = surfaceMatch ? surfaceMatch[1] : "#111827"

  // Inject default theme surface color into index.html
  const themeColorPlugin = {
    name: "theme-color-plugin",
    transformIndexHtml(html) {
      return html.replace("%THEME_SURFACE_COLOR%", defaultThemeColor)
    },
  }

  return {
    define: {
      __APP_VERSION__: JSON.stringify(packageJson.version),
      __APP_HOMEPAGE__: JSON.stringify(packageJson.homepage),
    },
    plugins: [
      themeColorPlugin,
      imageProxyPlugin,
      apacheConfigPlugin,
      react(),
      VitePWA({
        strategies: "injectManifest",
        srcDir: "src",
        filename: "service-worker.js",
        manifest: {
          lang: "en",
          short_name: "TropoDisc",
          name: "TropoDisc – A universal music collection manager",
          description:
            "Organize your collection, enrich it with your own metadata, and locate albums instantly using LED strips",
          translations: {
            fr: {
              name: "TropoDisc – Un gestionnaire universel de collection musicale",
              description:
                "Organisez votre collection, enrichissez-la avec vos propres métadonnées, et localisez instantanément vos albums grâce à des bandes LED.",
            },
          },
          icons: [
            {
              src: "icon-192.png",
              sizes: "192x192",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "icon-512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "icon-maskable-512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "maskable",
            },
          ],
          start_url: "/",
          id: "/",
          display: "standalone",
          theme_color: defaultThemeColor,
          background_color: defaultThemeColor,
        },
        injectManifest: {
          globPatterns: ["**/*.{js,css,html,ico,png,svg,json}"],
        },
      }),
    ],
    server: {
      port: 3000,
      proxy: proxy,
    },
    build: {
      outDir: "build",
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes("node_modules")) {
              if (
                id.includes("react/") ||
                id.includes("react-dom/") ||
                id.includes("scheduler/") ||
                id.includes("prop-types/")
              ) {
                return "react-core"
              }
              if (id.includes("react-bootstrap") || id.includes("bootstrap")) {
                return "vendor-bootstrap"
              }
              if (id.includes("@fortawesome")) {
                return "vendor-icons"
              }
              return "vendor-others"
            }
          },
        },
      },
    },
    test: {
      globals: true,
      environment: "jsdom",
      setupFiles: "./src/setupTests.js",
    },
  }
})
