import { defineConfig, loadEnv } from "vite"
import react from "@vitejs/plugin-react"
import { VitePWA } from "vite-plugin-pwa"
import fs from "fs"

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "")
  const packageJson = JSON.parse(fs.readFileSync("./package.json", "utf8"))

  // Derive User-Agent string dynamically from package metadata
  const appName = "TropoCine"
  const userAgent = `${appName}/${packageJson.version} (${packageJson.homepage})`

  const proxy = {}

  if (env.TMDB_TOKEN) {
    const token = env.TMDB_TOKEN
    proxy["/api/tmdb"] = {
      target: "https://api.themoviedb.org",
      changeOrigin: true,
      rewrite: (path) => path.replace(/^\/api\/tmdb/, ""),
      headers: {
        Authorization: `Bearer ${token}`,
        "User-Agent": userAgent,
      },
      configure: (proxyServer) => {
        proxyServer.on("proxyRes", (proxyRes) => {
          delete proxyRes.headers["set-cookie"]
        })
      },
    }
  }

  proxy["/api/tmdb-image"] = {
    target: "https://image.tmdb.org",
    changeOrigin: true,
    rewrite: (path) => path.replace(/^\/api\/tmdb-image/, ""),
    headers: {
      "User-Agent": userAgent,
    },
    configure: (proxyServer) => {
      proxyServer.on("proxyRes", (proxyRes) => {
        delete proxyRes.headers["set-cookie"]
        proxyRes.headers["access-control-allow-origin"] = "*"
      })
    },
  }

  // Image proxy middleware to bypass CORS for client-side ZIP export
  const imageProxyPlugin = {
    name: "image-proxy-plugin",
    configureServer(server) {
      server.middlewares.use("/api/proxy-image", async (req, res) => {
        const targetUrl = new URL(req.url, "http://localhost").searchParams.get(
          "url",
        )

        if (!targetUrl) {
          res.statusCode = 400
          res.end("Missing url parameter")
          return
        }

        try {
          const response = await fetch(targetUrl, {
            headers: {
              "User-Agent": userAgent,
            },
          })

          if (!response.ok) {
            res.statusCode = response.status
            res.end("Failed to fetch image from target server")
            return
          }

          const arrayBuffer = await response.arrayBuffer()
          const contentType =
            response.headers.get("content-type") || "image/jpeg"

          res.setHeader("Content-Type", contentType)
          res.setHeader("Access-Control-Allow-Origin", "*")
          res.end(Buffer.from(arrayBuffer))
        } catch {
          res.statusCode = 500
          res.end("Internal error proxying image")
        }
      })
    },
  }

  // Emit .htaccess and Apache configuration fragments for deployments
  const apacheConfigPlugin = {
    name: "apache-config-plugin",
    generateBundle() {
      const htaccessContent = `# Auto-generated by Vite build
<IfModule mod_headers.c>
    # Set dynamic User-Agent for reverse proxy requests
    RequestHeader set User-Agent "${userAgent}"

    # Cache control for service worker and entry point
    <Files "service-worker.js">
        Header set Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    </Files>
    <Files "index.html">
        Header set Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    </Files>
</IfModule>

# Single Page Application routing fallback
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\\.html$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
</IfModule>

# Deny direct web access to server configuration and log files
<FilesMatch "\\.(conf|log)$">
    Require all denied
</FilesMatch>
`
      this.emitFile({
        type: "asset",
        fileName: ".htaccess",
        source: htaccessContent,
      })

      const headersContent = `# Auto-generated by Vite build
<IfModule mod_headers.c>
    # Set dynamic User-Agent for reverse proxy requests
    RequestHeader set User-Agent "${userAgent}"

    # Strip upstream Set-Cookie headers to prevent invalid domain cookie errors in browsers
    Header unset Set-Cookie
    Header always unset Set-Cookie
</IfModule>
`
      this.emitFile({
        type: "asset",
        fileName: "headers.conf",
        source: headersContent,
      })
    },
  }

  // Extract theme surface colors from CSS tokens (single source of truth)
  const themesCssPath = new URL(
    "../../packages/react/src/themes.css",
    import.meta.url,
  )
  const themesCss = fs.readFileSync(themesCssPath, "utf8")
  const defaultTheme = "blue"

  const themeColors = {}
  const themeBlockRegex = /(?:\[data-theme="([^"]+)"\]|:root)[^{]*\{([^}]+)\}/g
  let blockMatch
  while ((blockMatch = themeBlockRegex.exec(themesCss)) !== null) {
    const themeName = blockMatch[1] || "dark"
    const colorMatch = blockMatch[2].match(
      /--tropo-surface:\s*(#[0-9a-f]{3,8})/i,
    )
    if (colorMatch) {
      themeColors[themeName] = colorMatch[1]
    }
  }

  const defaultThemeColor = themeColors[defaultTheme] || "#0d1f35"

  // Inject theme surface colors into index.html
  const themeColorPlugin = {
    name: "theme-color-plugin",
    transformIndexHtml(html) {
      return html
        .replace("%THEME_SURFACE_COLOR%", defaultThemeColor)
        .replace("%THEME_COLORS_MAP%", JSON.stringify(themeColors))
    },
  }

  return {
    server: {
      port: 3001,
      proxy,
    },
    build: {
      outDir: "build",
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes("node_modules")) {
              if (
                id.includes("react/") ||
                id.includes("react-dom/") ||
                id.includes("scheduler/") ||
                id.includes("prop-types/")
              ) {
                return "react-core"
              }
              if (id.includes("react-bootstrap") || id.includes("bootstrap")) {
                return "vendor-bootstrap"
              }
              if (id.includes("@fortawesome")) {
                return "vendor-icons"
              }
              return "vendor-others"
            }
          },
        },
      },
    },
    plugins: [
      react(),
      themeColorPlugin,
      imageProxyPlugin,
      apacheConfigPlugin,
      VitePWA({
        strategies: "injectManifest",
        srcDir: "src",
        filename: "service-worker.js",
        manifest: {
          lang: "en",
          short_name: "TropoCine",
          name: "TropoCine – A universal film collection manager",
          description:
            "Organize your collection, discover directors and actors, and explore your films",
          translations: {
            fr: {
              name: "TropoCine – Un gestionnaire universel de collection de films",
              description:
                "Organisez votre collection, découvrez réalisateurs et acteurs, et explorez vos films.",
            },
          },
          icons: [
            {
              src: "icon-192.png",
              sizes: "192x192",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "icon-512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "icon-maskable-512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "maskable",
            },
          ],
          start_url: "/",
          id: "/",
          display: "standalone",
          theme_color: defaultThemeColor,
          background_color: defaultThemeColor,
        },
        injectManifest: {
          globPatterns: ["**/*.{js,css,html,ico,png,svg,json}"],
        },
      }),
    ],
    define: {
      __APP_NAME__: JSON.stringify("TropoCine"),
      __APP_VERSION__: JSON.stringify(packageJson.version),
      __APP_HOMEPAGE__: JSON.stringify(packageJson.homepage),
    },
  }
})
